"""Sherwood SDK: pay x402 resources with USDG and use the ZKx8004 registry on Robinhood Chain."""

from .client import PaidResponse, X402Client
from .commitments import (
    agent_id,
    capability_hash,
    canonical_inputs,
    config_commitment,
    create_salt,
    proof_commitment,
    proof_nullifier,
    result_hash,
)
from .errors import (
    PaymentError,
    PaymentRequiredError,
    PriceLimitExceededError,
    RegistryRevertError,
    RpcError,
    SettlementFailedError,
    SherwoodError,
    TransactionFailedError,
    UnknownNetworkError,
)
from .networks import MAINNET, NETWORKS, TESTNET, Network, get_network
from .registry import (
    Agent,
    ProofAnchor,
    RegistryEvent,
    RegistryReader,
    RegistryWriter,
    TransactionResult,
    deploy_contract,
    send_transaction,
)
from .rpc import JsonRpcClient
from .x402 import (
    PaymentPayload,
    PaymentRequirements,
    SettlementResponse,
    TransferAuthorization,
    VerifyResult,
    create_authorization,
    decode_header,
    encode_header,
    format_usdg,
    sign_authorization,
    to_usdg_units,
    verify_authorization_offline,
)

__version__ = "0.1.0"

__all__ = [
    "MAINNET",
    "NETWORKS",
    "TESTNET",
    "Agent",
    "JsonRpcClient",
    "Network",
    "PaidResponse",
    "PaymentError",
    "PaymentPayload",
    "PaymentRequiredError",
    "PaymentRequirements",
    "PriceLimitExceededError",
    "ProofAnchor",
    "RegistryEvent",
    "RegistryReader",
    "RegistryRevertError",
    "RegistryWriter",
    "RpcError",
    "SettlementFailedError",
    "SettlementResponse",
    "SherwoodError",
    "TransactionFailedError",
    "TransactionResult",
    "TransferAuthorization",
    "UnknownNetworkError",
    "VerifyResult",
    "X402Client",
    "__version__",
    "agent_id",
    "canonical_inputs",
    "capability_hash",
    "config_commitment",
    "create_authorization",
    "create_salt",
    "decode_header",
    "deploy_contract",
    "encode_header",
    "format_usdg",
    "get_network",
    "proof_commitment",
    "proof_nullifier",
    "result_hash",
    "send_transaction",
    "sign_authorization",
    "to_usdg_units",
    "verify_authorization_offline",
]
