/**
 * Compiles contracts/ZKx8004Registry.sol with solc-js and writes a typed
 * artifact (ABI + bytecode) that the app and scripts import.
 *
 * Run with: npm run contracts:compile
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import solc from "solc";

const ROOT = process.cwd();
const SOURCE = path.join(ROOT, "contracts", "ZKx8004Registry.sol");
const ARTIFACT = path.join(ROOT, "src", "lib", "chain", "registry-artifact.ts");
const EVM_VERSION = "cancun";
const OPTIMIZER_RUNS = 200;

interface CompilerMessage {
  severity: "error" | "warning" | "info";
  formattedMessage: string;
}

interface CompilerOutput {
  errors?: CompilerMessage[];
  contracts: Record<string, Record<string, { abi: unknown[]; evm: { bytecode: { object: string } } }>>;
}

const input = {
  language: "Solidity",
  sources: { "ZKx8004Registry.sol": { content: readFileSync(SOURCE, "utf8") } },
  settings: {
    evmVersion: EVM_VERSION,
    optimizer: { enabled: true, runs: OPTIMIZER_RUNS },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input))) as CompilerOutput;
const messages = output.errors ?? [];
messages.filter((message) => message.severity !== "error").forEach((message) => console.warn(message.formattedMessage));

const errors = messages.filter((message) => message.severity === "error");
if (errors.length) {
  errors.forEach((message) => console.error(message.formattedMessage));
  process.exit(1);
}

const contract = output.contracts["ZKx8004Registry.sol"].ZKx8004Registry;
const artifact = `// Generated by scripts/compile-contracts.ts. Do not edit by hand.

export const REGISTRY_COMPILER = {
  solc: ${JSON.stringify(solc.version())},
  evmVersion: ${JSON.stringify(EVM_VERSION)},
  optimizerRuns: ${OPTIMIZER_RUNS},
} as const;

export const REGISTRY_ABI = ${JSON.stringify(contract.abi, null, 2)} as const;

export const REGISTRY_BYTECODE = "0x${contract.evm.bytecode.object}" as const;
`;

writeFileSync(ARTIFACT, artifact);
console.log(`Compiled ZKx8004Registry with solc ${solc.version()} → ${path.relative(ROOT, ARTIFACT)} (${contract.evm.bytecode.object.length / 2} bytes)`);
